name: build_all
on: push

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build all
      run: |
         cmake -S. -Bbuild
         cmake --build build
      shell: bash
